import { PRIV_TOKEN, USER } from "./config";
import { gh } from "./github-client";

const LOC_QUERY = `
query($owner: String!, $name: String!, $id: ID!, $cursor: String) {
  repository(owner: $owner, name: $name) {
    defaultBranchRef { target { ... on Commit {
      history(first: 100, author: { id: $id }, after: $cursor) {
        pageInfo { hasNextPage endCursor }
        nodes { message additions deletions }
      }
    } } }
  }
}`;

interface LocPage {
	repository: {
		defaultBranchRef: {
			target: {
				history: {
					pageInfo: { hasNextPage: boolean; endCursor: string | null };
					nodes: { message: string; additions: number; deletions: number }[];
				};
			};
		} | null;
	};
}

// Commits generated by automation (dependency bumps, lockfile regens, this very
// profile-card bot, merge commits, ...) inflate LOC without reflecting hand-written
// work, so they're excluded by matching the commit subject line.
const AUTO_GENERATED_COMMIT_PATTERNS = [
	/^chore\(deps\)/i,
	/^bump\b/i,
	/^merge pull request/i,
	/^update .*(lock|dependenc)/i,
	/^regenerate/i,
	/^update profile card stats/i,
	/\[skip ci\]/i,
	/^dependabot/i,
];

function isAutoGeneratedCommit(message: string): boolean {
	const subject = message.split("\n", 1)[0];
	return AUTO_GENERATED_COMMIT_PATTERNS.some((p) => p.test(subject));
}

// REST's stats/contributors endpoint answers 202 (still computing) forever for
// the Actions token, so walk each repo's own commit history via GraphQL instead.
async function fetchRepoLoc(
	name: string,
	userId: string,
): Promise<{ add: number; del: number; skipped: number }> {
	let add = 0;
	let del = 0;
	let skipped = 0;
	let cursor: string | null = null;
	for (;;) {
		const data: LocPage = await gh<LocPage>(
			LOC_QUERY,
			{ owner: USER, name, id: userId, cursor },
			PRIV_TOKEN,
		);
		const ref = data.repository.defaultBranchRef;
		if (!ref) break; // empty repo
		const h = ref.target.history;
		for (const commit of h.nodes) {
			if (isAutoGeneratedCommit(commit.message)) {
				skipped++;
				continue;
			}
			add += commit.additions;
			del += commit.deletions;
		}
		if (!h.pageInfo.hasNextPage) break;
		cursor = h.pageInfo.endCursor;
	}
	return { add, del, skipped };
}

export async function fetchLoc(
	repoNames: string[],
	userId: string,
): Promise<{ add: number; del: number }> {
	const results = await Promise.all(
		repoNames.map((name) =>
			fetchRepoLoc(name, userId).catch((err) => {
				console.error(`loc ${name}:`, err);
				return { add: 0, del: 0, skipped: 0 };
			}),
		),
	);
	const totals = results.reduce(
		(sum, r) => ({
			add: sum.add + r.add,
			del: sum.del + r.del,
			skipped: sum.skipped + r.skipped,
		}),
		{ add: 0, del: 0, skipped: 0 },
	);
	console.log(
		`loc: ${totals.add}++ ${totals.del}-- across ${repoNames.length} repos ` +
			`(${totals.skipped} automated commits excluded)`,
	);
	return { add: totals.add, del: totals.del };
}
